Our question is:
Broad question: We would like to know which "kinds" of players are most likely to contribute a large amount of data so that we can target those players in our recruiting efforts.

Specific: Can the Age and experience of a player be used to predict the sum total of hours played across multiple sessions of PLAICraft?

Since the research team is looking for 'kinds' of players, we include Age as demographic information. We decided against including gender because the data is lacking in many observations for most genders, and so we don't have sufficient training data to use it as a predictor. experience is the one additional detail for 'type' of player, and we convert it from 5 discrete factors into a linear scale of 1-5 in the order Amateur, Beginner, Regular, Veteran, and Pro.

The researchers are asking to identify predictors for players who contribute a "large amount" of data which could be considered categorical, but we plan to treat it as a regression problem where we predict the numerical value of played_hours for a given type of player. This gives the researchers the ability to define their own cutoff for what minimum number of hours is considered 'large'.

In [7]:
library(tidyverse)
library(lubridate)

In [8]:
players<-read_csv("players.csv")
head(players)

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

In [19]:
sessions<-read_csv("sessions.csv")
head(sessions)

Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  hashedEmail
1 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
4 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
5 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
6 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
  start_time       end_time         original_start_time original_end_time
1 30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2 17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3 25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
4 25/07/2024 03:22 25/07/2024 03:58 1.72188e+12         1.72188e+12
5 25/05/2024 16:01 25/05/2024 16:12 1.71665e+12         1.71665e+12
6 23/06/2024 15:08 23/06/2024 17:10 1.71916e+12         1.71916e+12

In [20]:
mutate(sessions,duration=dmy_hm(end_time)-dmy_hm(start_time),week_day=weekdays(dmy_hm(start_time)))

     hashedEmail
1    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2    36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3    f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
4    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
5    36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
6    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
7    fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
8    ad6390295640af1ed0e45ffc58a53b2d9074b0eea694b16210addd44d7c81f83
9    96e190b0bf3923cd8d349eee467c09d1130af143335779251492eb4c2c058a5f
10   36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
11   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
12   f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
13   f2826fb8dbce4d450348f99cb27ade184b713998d9679780442efaaf218038f2
14   b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
15   24d4892c2c3ce11d3e54c3bf31ee218901cac7a2f564911d67424c8fdf0874fe
16   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
17   88247d9a46fc214a12485dcbcbb03a8ddebfe8c1ec5fe209cd660147625c8e62
18   f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
19   36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
20   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
21   bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
22   36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
23   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
24   ad6390295640af1ed0e45ffc58a53b2d9074b0eea694b16210addd44d7c81f83
25   ad6390295640af1ed0e45ffc58a53b2d9074b0eea694b16210addd44d7c81f83
26   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
27   36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
28   bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
29   b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
30   fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
⋮    ⋮
1506 ad6390295640af1ed0e45ffc58a53b2d9074b0eea694b16210addd44d7c81f83
1507 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
1508 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
1509 b3510c708bd50bf9f75e6e02bb6fe14edb705e0ea671ee769a45c613750e8b58
1510 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
1511 e74c60a92c0100e7240be56d66969db85856152b048c639331a3595f901461ae
1512 b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
1513 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1514 e74c60a92c0100e7240be56d66969db85856152b048c639331a3595f901461ae
1515 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1516 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1517 a1e0438d568b9c05a93cadaf99969e4d44794d19dea31edd723cbc916f878c33
1518 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1519 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
1520 55d24216db39c27e1f17cc43d3127cbf8ed76ada6d098202b53ded319855e2c1
1521 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1522 b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
1523 b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
1524 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1525 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1526 18936844e06b6c7871dce06384e2d142dd86756941641ef39cf40a9967ea14e3
1527 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1528 18936844e06b6c7871dce06384e2d142dd86756941641ef39cf40a9967ea14e3
1529 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
1530 b622593d2ef8b337dc554acb307d04a88114f2bf453b18fb5d2c80052aeb2319
1531 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
1532 7a4686586d290c67179275c7c3dfb4ea02f4d317d9ee0e2cee98baa27877a875
1533 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1534 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1535 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
     start_time       end_time         original_start_time original_end_time
1    30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2    17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3    25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
4    25/07/2024 03:22 25/07/2024 03:58 1.72188e+12         1.72188e+12
5    25/05/2024 16:01 25/05/2024 16:12 1.71665e+12         1.71665e+12
6    23/06/2024 15:08 23/06/2024 17:10 1.71916e+12         1.71916e+12
7    15/04/2024 07:12 15/04/2024 07:21 1.71317e+12         1.71317e+12
8    21/09/2024 02:13 21/09/2024 02:30 1.72688e+12         1.72689e+12
9    21/06/2024 02:31 21/06/2024 02:49 1.71894e+12         1.71894e+12
10   16/05/2024 05:13 16/05/2024 05:52 1.71584e+12         1.71584e+12
11   03/07/2024 01:31 03/07/2024 01:35 1.71997e+12         1.71997e+12
12   30/07/2024 15:15 30/07/2024 15:43 1.72235e+12         1.72235e+12
13   24/08/2024 02:32 24/08/2024 03:12 1.72447e+12         1.72447e+12
14   18/08/2024 00:51 18/08/2024 03:15 1.72394e+12         1.72395e+12
15   23/05/2024 18:12 23/05/2024 18:22 1.71649e+12         1.71649e+12
16   11/07/2024 05:20 11/07/2024 05:57 1.72068e+12         1.72068e+12
17   01/08/2024 23:12 01/08/2024 23:23 1.72255e+12         1.72255e+12
18   08/08/2024 00:21 08/08/2024 01:35 1.72308e+12         1.72308e+12
19   03/06/2024 00:22 03/06/2024 00:33 1.71737e+12         1.71737e+12
20   31/07/2024 02:58 31/07/2024 03:21 1.72239e+12         1.72240e+12
21   04/07/2024 02:25 04/07/2024 04:05 1.72006e+12         1.72007e+12
22   07/05/2024 19:23 07/05/2024 19:34 1.71511e+12         1.71511e+12
23   27/06/2024 21:40 27/06/2024 21:48 1.71952e+12         1.71952e+12
24   30/05/2024 06:11 30/05/2024 06:57 1.71705e+12         1.71705e+12
25   26/07/2024 23:09 26/07/2024 23:16 1.72204e+12         1.72204e+12
26   09/07/2024 17:56 09/07/2024 18:02 1.72055e+12         1.72055e+12
27   04/05/2024 21:41 04/05/2024 21:50 1.71486e+12         1.71486e+12
28   26/06/2024 01:58 26/06/2024 03:35 1.71937e+12         1.71937e+12
29   30/06/2024 16:21 30/06/2024 20:32 1.71976e+12         1.71978e+12
30   22/08/2024 03:02 22/08/2024 03:49 1.72430e+12         1.72430e+12
⋮    ⋮                ⋮                ⋮                   ⋮
1506 08/06/2024 16:14 08/06/2024 20:25 1.71786e+12         1.71788e+12
1507 02/06/2024 15:18 02/06/2024 16:53 1.71734e+12         1.71735e+12
1508 22/05/2024 00:51 22/05/2024 01:22 1.71634e+12         1.71634e+12
1509 29/08/2024 03:42 29/08/2024 04:11 1.72490e+12         1.72490e+12
1510 03/08/2024 22:33 04/08/2024 00:51 1.72272e+12         1.72273e+12
1511 28/08/2024 19:00 28/08/2024 20:26 1.72487e+12         1.72488e+12
1512 18/08/2024 21:54 19/08/2024 02:09 1.72402e+12         1.72403e+12
1513 23/05/2024 20:04 23/05/2024 20:20 1.71649e+12         1.71650e+12
1514 22/07/2024 08:02 22/07/2024 08:07 1.72164e+12         1.72164e+12
1515 02/06/2024 01:17 02/06/2024 01:21 1.71729e+12         1.71729e+12
1516 29/04/2024 04:14 29/04/2024 05:34 1.71436e+12         1.71437e+12
1517 27/04/2024 04:05 27/04/2024 05:48 1.71419e+12         1.71420e+12
1518 30/07/2024 03:44 30/07/2024 03:54 1.72231e+12         1.72231e+12
1519 28/05/2024 03:58 28/05/2024 04:04 1.71687e+12         1.71687e+12
1520 27/08/2024 17:22 27/08/2024 17:31 1.72478e+12         1.72478e+12
1521 12/06/2024 23:13 12/06/2024 23:32 1.71823e+12         1.71824e+12
1522 10/09/2024 00:20 10/09/2024 04:34 1.72593e+12         1.72594e+12
1523 04/08/2024 04:29 04/08/2024 08:01 1.72275e+12         1.72276e+12
1524 09/08/2024 02:43 09/08/2024 03:14 1.72317e+12         1.72317e+12
1525 23/05/2024 18:51 23/05/2024 18:58 1.71649e+12         1.71649e+12
1526 25/06/2024 01:08 25/06/2024 02:18 1.71928e+12         1.71928e+12
1527 19/05/2024 15:05 19/05/2024 17:02 1.71613e+12         1.71614e+12
1528 05/07/2024 04:29 05/07/2024 04:45 1.72015e+12         1.72015e+12
1529 22/06/2024 02:30 22/06/2024 04:22 1.71902e+12         1.71903e+12
1530 28/08/2024 23:31 29/08/2024 00:15 1.72489e+12         1.72489e+12
1531 10/05/2024 23:01 10/05/2024 23:07 1.71538e+12         1.71538e+12
1532 01/07/2024 04:08 01/07/2024 04:19 1.71981e+12         1.71981e+12
1533 28/07/2024 15:36 28/07/2024 15:57 1.72218e+12         1.72218e+12
1534 25/07/2024 06:15 25/07/2024 06:22 1.72189e+12         1.72189e+12
1535 20/05/2024 02:26 20/05/2024 02:45 1.71617e+12         1.71617e+12
     duration week_day
1     12 mins Sunday
2     13 mins Monday
3     23 mins Thursday
4     36 mins Thursday
5     11 mins Saturday
6    122 mins Sunday
7      9 mins Monday
8     17 mins Saturday
9     18 mins Friday
10    39 mins Thursday
11     4 mins Wednesday
12    28 mins Tuesday
13    40 mins Saturday
14   144 mins Sunday
15    10 mins Thursday
16    37 mins Thursday
17    11 mins Thursday
18    74 mins Thursday
19    11 mins Monday
20    23 mins Wednesday
21   100 mins Thursday
22    11 mins Tuesday
23     8 mins Thursday
24    46 mins Thursday
25     7 mins Friday
26     6 mins Tuesday
27     9 mins Saturday
28    97 mins Wednesday
29   251 mins Sunday
30    47 mins Thursday
⋮    ⋮        ⋮
1506 251 mins Saturday
1507  95 mins Sunday
1508  31 mins Wednesday
1509  29 mins Thursday
1510 138 mins Saturday
1511  86 mins Wednesday
1512 255 mins Sunday
1513  16 mins Thursday
1514   5 mins Monday
1515   4 mins Sunday
1516  80 mins Monday
1517 103 mins Saturday
1518  10 mins Tuesday
1519   6 mins Tuesday
1520   9 mins Tuesday
1521  19 mins Wednesday
1522 254 mins Tuesday
1523 212 mins Sunday
1524  31 mins Friday
1525   7 mins Thursday
1526  70 mins Tuesday
1527 117 mins Sunday
1528  16 mins Friday
1529 112 mins Saturday
1530  44 mins Wednesday
1531   6 mins Friday
1532  11 mins Monday
1533  21 mins Sunday
1534   7 mins Thursday
1535  19 mins Monday

In [22]:
session_feature<-mutate(sessions,duration=dmy_hm(end_time)-dmy_hm(start_time),week_day=weekdays(dmy_hm(start_time)))|>
group_by(hashedEmail)|>
summarize(mean_time=mean(duration),ds_time=sd(duration),n=n())
session_feature

    hashedEmail
1   0088b5e134c3f0498a18c7ea6b8d77b4b0ff1636fc93355ccc95b45423367832
2   060aca80f8cfbf1c91553a72f4d5ec8034764b05ab59fe8e1cf0eee9a7b67967
3   0ce7bfa910d47fc91f21a7b3acd8f33bde6db57912ce0290fa0437ce0b97f387
4   0d4d71be33e2bc7266ee4983002bd930f69d304288a8663529c875f40f1750f3
5   0d70dd9cac34d646c810b1846fe6a85b9e288a76f5dcab9c1ff1a0e7ca200b3a
6   11006065e9412650e99eea4a4aaaf0399bc338006f85e80cc82d18b49f0e2aa4
7   119f01b9877fc5ea0073d05602a353b91c4b48e4cf02f42bb8d661b46a34b760
8   18936844e06b6c7871dce06384e2d142dd86756941641ef39cf40a9967ea14e3
9   1a2b92f18f36b0b59b41d648d10a9b8b20a2adff550ddbcb8cec2f47d4d881d0
10  1d2371d8a35c8831034b25bda8764539ab7db0f63938696917c447128a2540dd
11  200db0417ee70863c7e2a0f214c737476fb86de5869d0b907a077d726357e687
12  20ae3f8b5323674fe6e537bc91928841cfc2a00c1b36522fd25370bb6fa89d36
13  22a78bfd44e46931261d06864b92cf9a8fd77fb02bec66cb71646dd9da222a0d
14  23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5
15  24d4892c2c3ce11d3e54c3bf31ee218901cac7a2f564911d67424c8fdf0874fe
16  25879aecc205544bc6505f9faf768356e0a3b7126057308ae3235f8a514e9a62
17  2917e2dacafed92d017b9f356ce90a442bea6e4ad59dbbb484a920398acb8974
18  2cfed571797b66cc810c32562fc5b0f70b5bec0f5250799245527135bbf9662e
19  336adf9b9070abb44eaec22a48b04d8cda6cf0c98a46eef37779a1dcb6f5b4bb
20  36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
21  3caa832978e0596779f4ee7c686c4592fb6de893925025d25bf26be9a8cd03f5
22  42382bb2af563e6979c5b84d288cbb49bb2ef90b1bcf196c2902da4ce20eb7f3
23  42eafe96ed5c1684e3b5cc614d1b01a117173d3ec6898abcf1177d9822bd39f7
24  4b01bce3f141289709e8278b02ba5d2aaa7105d7ccb9c7deb37670a80e332774
25  4bed6f49b672974f706aa7f020b4f29020326bf594520593557cd381a51559b8
26  4bfad3613c71ace05644bf210195d9fb0d3d9513753ad2f8a16d1a80699bb906
27  55d24216db39c27e1f17cc43d3127cbf8ed76ada6d098202b53ded319855e2c1
28  577aa5f15468252b1c6f32dcd515012923476292e30f95e6b4128c770e993f92
29  5a340c0e3d1aa3e579efc625bd3e5bca7fc25f7115b68e9411f457464bfd3df4
30  5afb9b4ba7f0bb42d4e4d72ee21be8a51131a7677f0519b4606fdbf770eec750
⋮   ⋮
96  d48302dee689942b60f7e9756eba99d0be030df0ab6f553904a9dbbc44d0b5d5
97  d51a8c57269fe347b4b7760ec29c420832cb36a11c47569a9200872831910c05
98  d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db299bd4fedb06a46ad5bb
99  d9473710057f7d42f36570f0be83817a4eea614029ff90cf50d8889cdd729d11
100 dbb20960cd4db4900dde7832e349dae46f7688583c8138b34785d9c7e509b5b9
101 dc73467f73263dd4a07838330dd1cc115aa3f8b03538911ee6aac048405939c4
102 e21a324ccf5c873bafe82e47d5137b36aa312ee4803eeb5cbc6cf945f9bb3f38
103 e3175c379bbb83c8786d2dd719cf844575aca24d2c81d643dc7f12f6227becf7
104 e3e1bef1ce259c995332635c0ec630a575713451cbe742d7ca93e4c03d0826df
105 e44041459da2102dc20147ed6f0db4753547be66fc4ddea037bafca64004de2d
106 e47ae138603b9a7d6e9b97554bac2daf0477b30e0a4f29ed9d3deacc3c7ec155
107 e74c60a92c0100e7240be56d66969db85856152b048c639331a3595f901461ae
108 ed3e6d043dee74fad932be44d0600f4502055198c511927b0c906f50b57d9582
109 f19e136ddde68f365afc860c725ccff54307dedd13968e896a9f890c40aea436
110 f1b432523542f90c61176a555ccb2144468d76c91a32d74082ab8c101f9d25b6
111 f2826fb8dbce4d450348f99cb27ade184b713998d9679780442efaaf218038f2
112 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9
113 f459ce1862ec9a43b6c714810390dfd632ed104eb11378b3a2a134b1b107bc75
114 f4f29f2465743ead8c3ce02fc84542afe33ae3c95ef56a42b8f7785550fe9e4a
115 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
116 f707d141be44b2bf963eb171dbd14599059b4dda09aa002ba95ead4fa67273a7
117 f7875ae87a61632030d5c4029ee8cf081be7047b2b4a9c04ab5a706f59786197
118 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
119 f9ac013b2f0bc2bd4928a6a0fc8a0aae8b5c4f2670cf9e18f547b7e72034c965
120 fb0005032363ec3b30c2ae668f78f5076b7e77de0c6a249e924eee608cd0a1fa
121 fc0224c81384770e93ca717f32713960144bf0b52ff67639433a5c06a653a882
122 fcab03c6d3079521e7f9665caed0f31fe3dae6b5ccb86e6cb58747a43aa8789f
123 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
124 fe218a05c6c3fc6326f4f151e8cb75a2a9fa29e22b110d4c311fb58fb211f471
125 fef4e1bed8c3f6dcd7bcd39ab21bd402386155b2ff8c8e53683e1d2793bf1ed1
    mean_time       ds_time    n
1    53.000000 mins 11.3137085   2
2    30.000000 mins         NA   1
3    11.000000 mins         NA   1
4    32.153846 mins 15.1978406  13
5    35.000000 mins 16.9705627   2
6    10.000000 mins         NA   1
7    50.000000 mins         NA   1
8    29.682927 mins 32.1911782  41
9    18.000000 mins         NA   1
10    5.000000 mins         NA   1
11   12.000000 mins         NA   1
12   23.000000 mins 16.9705627   2
13   43.000000 mins 21.2132034   2
14   50.000000 mins         NA   1
15   29.949367 mins 31.3916120  79
16    7.000000 mins         NA   1
17    5.000000 mins         NA   1
18    6.000000 mins         NA   1
19   88.666667 mins 45.7857329   3
20   29.792308 mins 23.8745741 130
21   12.000000 mins         NA   1
22   55.000000 mins         NA   1
23    5.363636 mins  0.9244163  11
24  121.000000 mins         NA   1
25  101.000000 mins         NA   1
26   11.000000 mins         NA   1
27          NA mins         NA   4
28   10.000000 mins         NA   1
29   16.500000 mins 17.6776695   2
30   14.000000 mins         NA   1
⋮   ⋮               ⋮          ⋮
96  10.00000 mins          NA    1
97  49.00000 mins          NA    1
98   5.00000 mins          NA    1
99  15.00000 mins          NA    1
100  7.00000 mins          NA    1
101  7.00000 mins          NA    1
102  6.00000 mins          NA    1
103 53.00000 mins          NA    1
104  5.00000 mins    2.412091   12
105 26.00000 mins          NA    1
106  7.00000 mins          NA    1
107 11.91489 mins   14.928569   47
108  5.00000 mins          NA    1
109 29.83333 mins   44.015528    6
110 13.00000 mins          NA    1
111 38.00000 mins   36.742346    7
112 85.00000 mins   74.020267    3
113 23.00000 mins    8.485281    2
114 20.50000 mins    9.192388    2
115 74.77778 mins   54.129711   27
116  8.00000 mins          NA    1
117 19.00000 mins          NA    1
118 62.55975 mins   57.135370  159
119 37.00000 mins   46.669048    2
120 52.00000 mins   28.786571    4
121 16.00000 mins          NA    1
122 80.00000 mins          NA    1
123 15.46774 mins   20.289425  310
124  9.00000 mins          NA    1
125 72.00000 mins          NA    1